WebCarFist/Models/InvoiceDetails.cs
using System;
using System.Collections.Generic;

namespace WebCarFist.Models
{
    public partial class InvoiceDetails
    {
        public int InvoiceId { get; set; }
        public int ProductId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }

        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}

WebCarFist/Areas/Admin/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;

namespace WebCarFist.Areas.Admin
{
    public class LoginModel : PageModel
    {
        private DatabaseContext db;
        public string Msg { get; set; }
        public LoginModel(DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
        }
        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("username");
            return Page();
        }
        public IActionResult OnPost(string username, string password)
        {
            if (Check(username, password) != null)
            {
                HttpContext.Session.SetString("username", username);
                return RedirectToPage("Dashboard");
            }
            else
            {
                Msg = "Invalid";
                return Page();
            }
        }
        private Account Check(string username, string password)
        {
            Account account = db.Account.SingleOrDefault(a => a.UserName.Equals(username));
            if (account != null)
            {
                if (password.Equals(account.Password) == true)
                {
                    return account;
                }
            }
            return null;
        }
    }
}

WebCarFist/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;


namespace WebCarFist.Pages
{
    public class CartModel : PageModel
    {
        private DatabaseContext db;
        public List<Item> cart { get; set; }

        public decimal Total { get; set; }
        public CartModel (DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            string sessionCart = HttpContext.Session.GetString("cart");
            Total = 0;
            if (sessionCart != null)
            {
                cart = JsonConvert.DeserializeObject<List<Item>>(sessionCart);
                Total = cart.Sum(it => it.product.Price * it.Quantity);
            }
        }

        public IActionResult OnPost(int[] quantity)
        {
            List<Item> items = JsonConvert.DeserializeObject<List<Item>>
                (HttpContext.Session.GetString("cart"));
            for (int i= 0; i < quantity.Length; i++)
            {
                items[i].Quantity = quantity[i];  
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(items));
            return RedirectToPage("Cart");
        }

        public IActionResult OnGetRemove(int id)
        {
            List<Item> items = JsonConvert.DeserializeObject<List<Item>>
                (HttpContext.Session.GetString("cart"));
            int index = exits(id, items);
            items.RemoveAt(index);
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(items));
            return RedirectToPage("Cart");
        }

        public IActionResult OnGetCheckout()
        {
            string username = HttpContext.Session.GetString("username");
            if(username == null)
            {
                return RedirectToPage("Login");
            }
            else
            {
                var account = db.Account.AsNoTracking().SingleOrDefault(a => a.UserName.Equals
                (username));
                //add new invoice
                var invoice = new Invoice
                {
                    Created = DateTime.Now,
                    Name="Invoice",
                    AccountId = account.Id
                };
                db.Invoice.Add(invoice);
                db.SaveChanges();

                //Add invoice details
                List<Item> items = JsonConvert.DeserializeObject<List<Item>>
                (HttpContext.Session.GetString("cart"));

                if(items != null)
                {
                    foreach(var item in items)
                    {
                        var invoiceDatails = new InvoiceDetails
                        {
                            InvoiceId = invoice.Id,
                            ProductId = item.product.Id,
                            Price = item.product.Price,
                            Quantity = item.Quantity,
                        };
                        db.InvoiceDetails.Add(invoiceDatails);
                        db.SaveChanges();
                    }
                }
                return RedirectToPage("Thanks");
            }
        }

        public IActionResult OnGetBuyNow(int id)
        {
            string sessionCart = HttpContext.Session.GetString("cart");
            Product product = db.Product.SingleOrDefault(p => p.Id == id);
            if (sessionCart == null)
            {
                List<Item> items = new List<Item>();
                items.Add(new Item
                {
                    product = new ProductCart { 

                        Id = product.Id,
                        Name = product.Name,
                        Price = product.Price,
                        Photo = product.Photo,
                    },
                    Quantity = 1
                });
                HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(items));
            }
            else
            {
                List<Item> items = JsonConvert.DeserializeObject<List<Item>>
                (HttpContext.Session.GetString("cart"));
                int index = exits(id, items);
                if(index == -1)
                {
                    items.Add(new Item
                    {
                        product = new ProductCart
                        {

                            Id = product.Id,
                            Name = product.Name,
                            Price = product.Price,
                            Photo = product.Photo,
                        },
                        Quantity = 1
                    });
                }
                else
                {
                    items[index].Quantity++;
                }
                HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(items));
            }
            return RedirectToPage("Cart");
        }

        private int exits(int id, List<Item> items)
        {
            for(var i=0; i < items.Count; i++)
            {
                if(items[i].product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

WebCarFist/Pages/Categories.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;

namespace WebCarFist.Pages
{
    public class CategoriesModel : PageModel
    {
        private DatabaseContext db;
        [BindProperty(Name = "id", SupportsGet = true)]
        public int Id { get; set; }
        public Category category { get; set; }
        public List<Product> products { get; set; }
        public CategoriesModel(DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            category = db.Category.Find(Id);
            products = db.Product.Where(p => p.CategoryId == Id).ToList();
        }
    }
}

WebCarFist/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;

namespace WebCarFist.Pages
{
    public class DetailsModel : PageModel
    {
        private DatabaseContext db;

        [BindProperty(Name ="id", SupportsGet =true)]
        public int Id { get; set; }

        public Product product { get; set; }
        public DetailsModel(DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            product = db.Product.Find(Id);
        }
    }
}

WebCarFist/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebCarFist.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebCarFist/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;

namespace WebCarFist.Pages
{
    public class IndexModel : PageModel
    {
        private DatabaseContext db;
        public List<Product> NewProducts { get; set; }
        

        public IndexModel(DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            NewProducts = db.Product.ToList();
        }
    }
}

WebCarFist/Pages/InvoiceDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;

namespace WebCarFist.Pages
{
    public class InvoiceDetailsModel : PageModel
    {
        private DatabaseContext db;

        [BindProperty(Name ="id", SupportsGet =true)]
        public int Id { get; set; }
        public Invoice invoice { get; set; }
        public decimal Total { get; set; }

        public InvoiceDetailsModel (DatabaseContext _db)
        {
            db = _db;
        }
        public IActionResult OnGet()
        {
            string username = HttpContext.Session.GetString("username");
            if (username == null)
            {
                return RedirectToPage("Login");
            }
            else
            {
                invoice = db.Invoice.Find(Id);
                Total = invoice.InvoiceDetails.Sum(i => i.Price * i.Quantity);
                return Page();
            }
             
        }
    }
}

WebCarFist/Pages/InvoiceManagement.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using WebCarFist.Models;

namespace WebCarFist.Pages
{
    public class InvoiceManagementModel : PageModel
    {
        private DatabaseContext db;
        public List<Invoice> invoices { get; set; }
        public InvoiceManagementModel (DatabaseContext _db)
        {
            db = _db;
        }
        public IActionResult OnGet()
        {
            string username = HttpContext.Session.GetString("username");
            if (username == null)
            {
                return RedirectToPage("Login");
            }
            else
            {
                var account = db.Account.AsNoTracking().SingleOrDefault(a => a.UserName.Equals
                (username));
                invoices = db.Invoice.Where(i => i.AccountId == account.Id).OrderByDescending(i => i.Id).ToList();
                return Page();
            }
        }
    }
}

WebCarFist/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;

namespace WebCarFist.Pages
{
    public class LoginModel : PageModel
    {
        private DatabaseContext db;
        public string Msg { get; set; }
        public LoginModel(DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
        }
        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("username");
            return Page();
        }
        public IActionResult OnPost(string username, string password)
        {
            if(Check(username, password) != null)
            {
                HttpContext.Session.SetString("username", username);
                return RedirectToPage("Welcome");
            }
            else
            {
                Msg = "Invalid";
                return Page();
            }
        }
        private Account Check(string username, string password)
        {
            Account account = db.Account.SingleOrDefault(a => a.UserName.Equals(username));
            if(account != null)
            {
                if (password.Equals (account.Password) == true)
                {
                    return account;
                }
            }
            return null;
        }
    }
}

WebCarFist/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebCarFist.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebCarFist/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;
using BCrypt;

namespace WebCarFist.Pages
{
    public class RegisterModel : PageModel
    {
        private DatabaseContext db;

        [BindProperty]
        public Account account { get; set; }

        public RegisterModel(DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            account = new Account();
        }
        public IActionResult OnPost()
        {
            //account.Password = BCrypt.Net.BCrypt.HashPassword(account.Password);         
            db.Account.Add(account);
            db.SaveChanges();
            //RoleAccount roleAccount = new RoleAccount
            //{
              //  AccountId = account.Id,
                //RoleId = 2
           // };
            //db.RoleAccount.Add(roleAccount);
            //db.SaveChanges();
            return RedirectToPage("login");
        }
    }
}

WebCarFist/Pages/Search.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebCarFist.Models;

namespace WebCarFist.Pages
{
    public class SearchModel : PageModel
    {
        private DatabaseContext db;
        [BindProperty(Name = "id", SupportsGet = true)]
        public int categoryId { get; set; }

        [BindProperty(Name = "keyword", SupportsGet = true)]
        public string keyword { get; set; }
        public IEnumerable<Product> products { get; set; }
        public SearchModel(DatabaseContext _db)
        {
            db = _db;
        }
        public void OnGet()
        {
            products= db.Product.Where(p => p.Name.Contains(keyword)).ToList();
            
        }

    }
}

WebCarFist/Pages/Thanks.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebCarFist.Pages
{
    public class ThanksModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebCarFist/Pages/Welcome.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebCarFist.Pages
{
    public class WelcomeModel : PageModel
    {
        public string Username { get; set; }
        public IActionResult OnGet()
        {
            string usernameSession = HttpContext.Session.GetString("username");
            if(usernameSession == null)
            {
                return RedirectToPage("Login");
            }
            else
            {
                Username = usernameSession;
                return Page();
            }
        }
    }
}

WebCarFist/Pages/Cart.cshtml
@page
@model WebCarFist.Pages.CartModel

@{
    ViewData["Title"] = "Cart";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-page="Index">Home</a></li>
            <li class="breadcrumb-item active">Cart</li>
        </ul>
    </div>
</div>
<form method="post" asp-page="cart">
    <div class="cart-page">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <div class="cart-page-inner">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>Product</th>
                                        <th>Price</th>
                                        <th>Quantity/Update
                                        <button type="submit" class="btn-plus"><i class="far fa-save"></i></button>
                                        </th>
                                        <th>Total</th>
                                        <th>Remove</th>
                                    </tr>
                                </thead>
                                <tbody class="align-middle">
                                    @foreach (var item in Model.cart)
                                    {
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <img src="~/product/@item.product.Photo" alt="Image">
                                                    <p>@item.product.Name</p>
                                                </div>
                                            </td>
                                            <td>$@item.product.Price</td>
                                            <td>
                                                <div class="qty">
                                                    <input name="quantity" type="number" min="1" placeholder="1" size="16" value="@item.Quantity">
                                                </div>
                                            </td>
                                            <td>$@(item.product.Price * item.Quantity )</td>
                                            <td>                 
                                                 <a class="btn-plus" asp-page="cart" asp-page-handler="remove" asp-route-id="@item.product.Id">
                                                  <i class="fa fa-trash"></i>
                                                  </a>
                                                                                          
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="cart-page-inner">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="cart-summary">
                                    <div class="cart-content">
                                        <h1>Cart Summary</h1>
                                        <h2>Grand Total<span>$@Model.Total</span></h2>
                                    </div>
                                    <a class="btn cart-btn" asp-page="cart" asp-page-handler="checkout">
                                        CheckOut
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

WebCarFist/Pages/Categories.cshtml
@page
@model WebCarFist.Pages.CategoriesModel
@using WebCarFist.Models
@{
    ViewData["Title"] = "Categories";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<!--
<div class="col-md-12">
    <div class="product-view-top">
        <div class="row">
            <div class="col-md-4">
                <div class="product-search">
                    <h3></h3>
                </div>
            </div>
        </div>
    </div>
</div> -->

@foreach (var product in Model.products)
{
    Product p = (Product)product;
    <div class="col-md-4">
        <div class="product-item">
            <div class="product-title">
                <a asp-page="Details" asp-route-id="@product.Id">@p.Name</a>
                <div class="ratting">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                </div>
            </div>
            <div class="product-image">
                <a asp-page="Details" asp-route-id="@product.Id">
                    <img src="~/product/@product.Photo" alt="Product Image">
                </a>
            </div>
            <div class="product-price">
                <h3>$@p.Price</h3>
                <a class="btn" asp-page="Cart" asp-page-handler="buynow" asp-route-id="@product.Id"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
            </div>
        </div>
    </div>

}

WebCarFist/Pages/Details.cshtml
@page
@model WebCarFist.Pages.DetailsModel
@using WebCarFist.Models
@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<div class="product-detail">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        <div class="product-detail-top">
                            <div class="row align-items-center">
                                <div class="col-md-3">
                                    <div class="product-slider-single normal-slider">
                                        <img src="~/product/@Model.product.Photo" alt="Product Image">
                                    </div>
                                </div>
                                <div class="col-md-7">
                                    <div class="product-content">
                                        <div class="title"><h2>@Model.product.Name</h2></div>
                                        <div class="ratting">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <div class="price">
                                            <h4>Price:</h4>
                                            <p>@Model.product.Price<span>$</span></p>
                                        </div>
                                        <div class="price">
                                            <h4>Amount:</h4> 
                                            <p>@Model.product.Quantity</p>
                                            </div>
                                        <div class="quantity">
                                                <h4>Quantity:</h4>
                                                <div class="qty">
                                                    <button class="btn-minus"><i class="fa fa-minus"></i></button>
                                                    <input type="text" value="1">
                                                    <button class="btn-plus"><i class="fa fa-plus" ></i></button>
                                                </div>
                                        </div>
                                            <div class="action">
                                                <a class="btn" asp-page="Cart" asp-page-handler="buynow" asp-route-id="@Model.product.Id"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
                                                <a class="btn" asp-page="Cart" asp-route-id="@Model.product.Id"><i class="fa fa-shopping-cart"></i>Buy Now</a>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>

                        <div class="row product-detail-bottom">
                            <div class="col-lg-12">
                                <ul class="nav nav-pills nav-justified">
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="pill" href="#description">Description</a>
                                    </li>
                                </ul>

                                <div class="tab-content">
                                    <div id="description" class="container tab-pane active">
                                        <h4>Product description</h4>
                                        <p>
                                            @Model.product.Description
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Side Bar Start -->
                    <!-- <div class="col-lg-4 sidebar">
        <div class="sidebar-widget category">
            <h2 class="title">Category</h2>
            <nav class="navbar bg-light">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-home"></i>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-shopping-bag"></i>Toyata</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-plus-square"></i>Honda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fa fa-female"></i>BMW</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="sidebar-widget tag">
            <h2 class="title">Tags Cloud</h2>
            <a href="#">Lorem ipsum</a>
            <a href="#">Vivamus</a>
            <a href="#">Phasellus</a>
            <a href="#">pulvinar</a>
            <a href="#">Curabitur</a>
            <a href="#">Fusce</a>
            <a href="#">Sem quis</a>
            <a href="#">Mollis metus</a>
            <a href="#">Sit amet</a>
            <a href="#">Vel posuere</a>
            <a href="#">orci luctus</a>
            <a href="#">Nam lorem</a>
        </div>
    </div>
    <!-- Side Bar End -->
                </div>
            </div>
</div>

WebCarFist/Pages/Index.cshtml
@page
@model WebCarFist.Pages.IndexModel
@using WebCarFist.Models
@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@foreach (var product in Model.NewProducts)
{
    Product p = (Product)product;
    <div class="col-md-4">
        <div class="product-item">
            <div class="product-title">
                <a asp-page="Details" asp-route-id="@product.Id">@p.Name</a>
                <div class="ratting">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                </div>
            </div>
            <div class="product-image">
                <a asp-page="Details" asp-route-id="@product.Id">
                    <img src="~/product/@product.Photo" alt="Product Image">
                </a>
            </div>
            <div class="product-price">
                <h3>$@p.Price</h3>
                <a class="btn" asp-page="Cart" asp-page-handler="buynow" asp-route-id="@product.Id"><i class="fa fa-shopping-cart"></i>Add to Cart</a>
            </div>
        </div>
    </div>
}
<div class="col-md-12">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            <li class="page-item active"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</div>

WebCarFist/Pages/Thanks.cshtml
@page
@model WebCarFist.Pages.ThanksModel
@using WebCarFist.Models
@{
    ViewData["Title"] = "Thanks";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<div class="breadcrumb-wrap">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-page="index">Home</a></li>
            <li class="breadcrumb-item active">Thanks</li>
        </ul>
    </div>
</div>

WebCarFist/Pages/Welcome.cshtml
@page
@model WebCarFist.Pages.WelcomeModel
@{
    ViewData["Title"] = "Welcome";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@using Microsoft.AspNetCore.Http;
<h1>Welcome @Model.Username</h1>